spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: "localhost:9200"

---

spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: develop
  elasticsearch:
    uris: "ec2-3-38-150-8.ap-northeast-2.compute.amazonaws.com:9200"
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: debug


---

spring:
  config:
    activate:
      on-profile: prod
  elasticsearch:
    uris: "localhost:9200"
