spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: "localhost:9200"

---

spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: develop
  elasticsearch:
    uris: "localhost:9200"

---

spring:
  config:
    activate:
      on-profile: prod
  elasticsearch:
    uris: "localhost:9200"
