spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    uris: "localhost:9200"

---

spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: develop
  elasticsearch:
    uris: "ec2-43-203-169-244.ap-northeast-2.compute.amazonaws.com:9200"

---

spring:
  config:
    activate:
      on-profile: prod
  elasticsearch:
    uris: "localhost:9200"
