FROM amazoncorretto:17
ARG JAR_FILE=wwooss-api/build/libs/wwooss-api-0.0.1-SNAPSHOT.jar

ARG SPRING_PROFILES_ACTIVE
RUN echo $SPRING_PROFILES_ACTIVE

ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE

ARG JASYPT_SECRET
ENV JASYPT_ENCRYPTOR_PASSWORD=$JASYPT_SECRET

COPY ${JAR_FILE} wwooss-api-app.jar

ENTRYPOINT ["java", "-jar", "-Djava.security.egd=file:/dev/./urandom", "-Djasypt.encrptor.password=$JASYPT_SECRET",
"/wwooss-api-app.jar"]
