FROM amazoncorretto:17
ARG JAR_FILE=wwooss-api/build/libs/wwooss-api-0.0.1-SNAPSHOT.jar
ARG SWAGGER_FILE=wwooss-api/src/main/resources/static/docs/open-api-3-wwooss-service.json

ARG SPRING_PROFILES_ACTIVE
RUN echo $SPRING_PROFILES_ACTIVE

ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE

COPY ${JAR_FILE} wwooss-api-app.jar
COPY ${SWAGGER_FILE} /var/lib/swagger

ENTRYPOINT ["java", "-jar", "-Djava.security.egd=file:/dev/./urandom", "/wwooss-api-app.jar"]
