server:
  servlet:
    context-path: /api
  port: 9090
spring:
  application:
    name: WWOOSS-SERVICE

---

spring:
  config:
    activate:
      on-profile: local
    import: application-rds.yaml
jwt:
  secret: ENC(pEvs1KBkGuc0I/Gtmh/3xn71ALKQGLRK6ghhWAqWl9tlHzpLD1gTDlv1nd/SuuoecG84nSyF1krULwuygcTclMb5azDX14CpxzqBrzUuKKd/QUs6/Gqt8zADB/XDtE6rmuPKYfYgv2CvaXSpkaRjBEdbvc2OjWB4)
  access-token-validity-in-milliseconds: 86400000
  refresh-token-validity-in-milliseconds: 86400000000

gcp:
  firebase:
    service-account: classpath:firebase/wwooss-c5a90-firebase-adminsdk-zh2zk-8a0d0bc64f.json

---

spring:
  config:
    activate:
      on-profile: develop
    import: application-rds.yaml
jwt:
  secret: ENC(pEvs1KBkGuc0I/Gtmh/3xn71ALKQGLRK6ghhWAqWl9tlHzpLD1gTDlv1nd/SuuoecG84nSyF1krULwuygcTclMb5azDX14CpxzqBrzUuKKd/QUs6/Gqt8zADB/XDtE6rmuPKYfYgv2CvaXSpkaRjBEdbvc2OjWB4)
  access-token-validity-in-milliseconds: 86400000
  refresh-token-validity-in-milliseconds: 86400000000

gcp:
  firebase:
    service-account: classpath:firebase/wwooss-c5a90-firebase-adminsdk-zh2zk-8a0d0bc64f.json
  web-client-id: ENC(gItC4oTf34ZS6uQInbQo0JQb2iWlNUMy8HPztWw5q5uhlht/EQu2qVdToB/sadCiZVBC9jAamhxarU6bTw57MtzY78x2gIbAwJBOzb1mVxOmX4fPzUOh7g==)
  client-secret: ENC(cDlEz74wcfRtlzuoQ1zkSN8bCMxN8CNt0hA2ey2pq40JjdHBjLjbcOeVazc11ciA)

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/killbill?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&tinyInt1isBit=false"
    username: root
    password: ENC(+p6g1owB0AzWumMOvy2V6gxkTjfJXzOX)
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      max-lifetime: 580000
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  batch:
    job:
      enabled: false

