job:
  step:
    chunk:
      size: 10
spring:
  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/wwooss?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone
    =Asia/Seoul&tinyInt1isBit=false"
    username: root
    password: pickit2022!
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      max-lifetime: 580000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
