server:
  servlet:
    context-path: /api
  port: 9100

---
spring:
  batch:
    job:
      enabled: false
  config:
    activate:
      on-profile: local
    import: application-rds.yaml

---

spring:
  batch:
    job:
      enabled: false
  config:
    activate:
      on-profile: develop
    import: application-rds.yaml

---

spring:
  config:
    activate:
      on-profile: test

