server:
  servlet:
    context-path: /api
  port: 9100

---
spring:
  batch:
    job:
      enabled: false
  config:
    activate:
      on-profile: local
    import: application-rds.yaml
job:
  step:
    chunk:
      size: 10

---

spring:
  batch:
    job:
      enabled: false
  config:
    activate:
      on-profile: develop
    import: application-rds.yaml
job:
  step:
    chunk:
      size: 10

---

spring:
  batch:
    job:
      enabled: false
  config:
    activate:
      on-profile: prod
    import: application-rds.yaml
job:
  step:
    chunk:
      size: 10
